sonar.projectKey=ritheshhebbar_devnotes-ci-cd
sonar.organization=k-s-rithesh-hebbar
sonar.projectName=DevNotes
sonar.sources=backend,frontend/src
sonar.host.url=https://sonarcloud.io
sonar.token=6b473f11d9bc59445546b269f0aa7a15d743eadf